"""initial_schema

Revision ID: 567ae56c545c
Revises: 
Create Date: 2026-07-14 10:36:39.812591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567ae56c545c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cio_explanation', sa.String(), nullable=True),
    sa.Column('tech_analyst', sa.JSON(), nullable=True),
    sa.Column('order_flow_analyst', sa.JSON(), nullable=True),
    sa.Column('macro_analyst', sa.JSON(), nullable=True),
    sa.Column('news_analyst', sa.JSON(), nullable=True),
    sa.Column('devils_advocate', sa.JSON(), nullable=True),
    sa.Column('risk_manager', sa.JSON(), nullable=True),
    sa.Column('pre_mortem_analyst', sa.JSON(), nullable=True),
    sa.Column('market_conditions', sa.JSON(), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('funding', sa.Float(), nullable=True),
    sa.Column('oi', sa.Float(), nullable=True),
    sa.Column('liquidations', sa.JSON(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.Column('mtf_correct', sa.Boolean(), nullable=True),
    sa.Column('funding_correct', sa.Boolean(), nullable=True),
    sa.Column('liquidation_correct', sa.Boolean(), nullable=True),
    sa.Column('orderflow_correct', sa.Boolean(), nullable=True),
    sa.Column('premortem_correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_sessions_symbol'), ['symbol'], unique=False)

    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_low', sa.Float(), nullable=False),
    sa.Column('entry_high', sa.Float(), nullable=False),
    sa.Column('entry_reference', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_initial', sa.Float(), nullable=False),
    sa.Column('stop_current', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=False),
    sa.Column('target_3', sa.Float(), nullable=False),
    sa.Column('target_runner', sa.Float(), nullable=False),
    sa.Column('target_stage', sa.Integer(), nullable=False),
    sa.Column('risk_per_unit', sa.Float(), nullable=False),
    sa.Column('risk_amount_usd', sa.Float(), nullable=False),
    sa.Column('notional_usd', sa.Float(), nullable=False),
    sa.Column('recommended_leverage', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('entry_timeout_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_session_id', sa.Integer(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('ai_review', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_signals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_signals_timeframe'), ['timeframe'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_signals_timeframe'))
        batch_op.drop_index(batch_op.f('ix_trade_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_trade_signals_status'))
        batch_op.drop_index(batch_op.f('ix_trade_signals_id'))

    op.drop_table('trade_signals')
    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_sessions_symbol'))
        batch_op.drop_index(batch_op.f('ix_analysis_sessions_id'))

    op.drop_table('analysis_sessions')
    # ### end Alembic commands ###
